name: CI

on: [push, pull_request]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt install python3
    - name: make test
      run: |
        make test

  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        brew install python3
    - name: make test
      run: |
        make test
